#!/bin/sh
set -eu

workspace_root=$1
generated_dir=$2

source_bytes=0
for file in \
  "$workspace_root/datascript/me/tonsky/persistent_sorted_set.cljc" \
  "$workspace_root"/datascript/me/tonsky/persistent_sorted_set/*.cljc \
  "$workspace_root"/test/datascript/upstream/*.cljc \
  "$workspace_root/test_runner/clojure/test.cljc" \
  "$workspace_root/test_runner/clojure/test_native.cljc" \
  "$workspace_root/test_runner/clojure/run.cljc" \
  "$workspace_root/test/datascript/upstream_test_support/datascript/test/core.cljc" \
  "$workspace_root"/test/datascript/upstream_tests/datascript/test/*.cljc
do
  source_bytes=$((source_bytes + $(wc -c < "$file")))
done

generated_bytes=0
for file in \
  "$generated_dir/datascript_conn_native.ml" \
  "$generated_dir/datascript_conn_native_base.ml" \
  "$generated_dir"/datascript_conn_native_test_*.ml
do
  generated_bytes=$((generated_bytes + $(wc -c < "$file")))
done

limit=$((source_bytes * 4))
if [ "$generated_bytes" -gt "$limit" ]; then
  printf 'DataScript code size exceeded: %s generated bytes > %s source bytes * 4\n' \
    "$generated_bytes" "$source_bytes" >&2
  exit 1
fi

ratio=$(awk -v generated="$generated_bytes" -v source="$source_bytes" \
  'BEGIN { printf "%.2f", generated / source }')
printf 'DataScript code size: %s / %s bytes = %sx\n' \
  "$generated_bytes" "$source_bytes" "$ratio"
