(test
 (name runtime_tests)
 (libraries alcotest lg.edn-backend.native lg-test.runtime))

(rule
 (target compatibility_native_chunk.ml)
 (deps
  ../clojure/test.cljc
  ../clojure/test_native.cljc
  compatibility.cljc
  ../../stdlib/lg_stdlib_native.state
  (package lg-test)
  ../runtime/lg_test_runtime.cma
  ../alcotest/lg_test_alcotest.cma
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   native
   --compile-files-from
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:../clojure/test.cljc}
   %{dep:../clojure/test_native.cljc}
   %{dep:compatibility.cljc}
   -o
   %{target})))

(rule
 (target compatibility_native.ml)
 (deps ../../stdlib/lg_stdlib_native.ml compatibility_native_chunk.ml)
 (action
   (with-stdout-to
    %{target}
    (progn
     (cat %{dep:../../stdlib/lg_stdlib_native.ml})
     (cat %{dep:compatibility_native_chunk.ml})))))

(executable
 (name compatibility_native)
 (modules compatibility_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.runtime lg.edn-backend.native lg-test.runtime lg-test.alcotest))

(rule
 (target compatibility_melange_chunk.ml)
 (deps
  ../clojure/test.cljc
  ../clojure/test_melange.cljc
  compatibility.cljc
  ../../stdlib/lg_stdlib_melange.state
  (package lg-test)
  ../runtime/lg_test_runtime.cma
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   melange
   --compile-files-from
   %{dep:../../stdlib/lg_stdlib_melange.state}
   %{dep:../clojure/test.cljc}
   %{dep:../clojure/test_melange.cljc}
   %{dep:compatibility.cljc}
   -o
   %{target})))

(rule
 (target compatibility_melange.ml)
 (deps ../../stdlib/lg_stdlib_melange.ml compatibility_melange_chunk.ml)
 (action
   (with-stdout-to
    %{target}
    (progn
     (cat %{dep:../../stdlib/lg_stdlib_melange.ml})
     (cat %{dep:compatibility_melange_chunk.ml})))))

(melange.emit
 (target compatibility-melange)
 (alias compatibility-melange)
 (module_systems es6)
 (modules compatibility_melange)
 (preprocess
  (pps melange.ppx))
 (compile_flags -w -27-32)
 (libraries
  lg.edn-backend
  lg.edn-backend.melange
  lg.runtime
  lg-test.runtime
  lg-test.melange))

(rule
 (alias runtest)
 (deps
  compatibility_native.exe
  (alias compatibility-melange)
  compatibility-melange/test_runner/test/compatibility_melange.js)
 (action
  (progn
   (run %{exe:compatibility_native.exe})
   (run
    node
    %{dep:compatibility-melange/test_runner/test/compatibility_melange.js}))))
