(library
 (name lg_runtime)
 (public_name lg.runtime)
 (modes native byte melange)
 (ocamlopt_flags :standard -no-g)
 (preprocess
  (per_module
   ((pps melange.ppx)
    runtime_array_melange
    runtime_math_melange
    runtime_number_melange
    runtime_seq_melange
    runtime_time_melange
    runtime_weak_melange)))
 (libraries rrbvec lg.edn-backend))
