(rule
 (targets lg_stdlib_native.ml lg_stdlib_native.state)
 (deps
  clojure/core.mil
  clojure/core.cljc
  clojure/string.mil
  clojure/string.cljc
  clojure/edn.mil
  clojure/edn.cljc
  cljs/reader.mil
  cljs/reader.cljc
  cljs/math.mil
  cljs/math.cljc
  clojure/core/protocols.cljc
  clojure/set.mil
  clojure/set.cljc
  clojure/data.mil
  clojure/data.cljc
  clojure/walk.mil
  clojure/walk.cljc
  clojure/zip.mil
  clojure/zip.cljc
  %{lib:lg.runtime:lg_runtime.cma}
  ../bin/lg_cli.exe)
 (action
  (run
   %{exe:../bin/lg_cli.exe}
   --target
   native
   --compile-files-state
   lg_stdlib_native.state
   %{dep:clojure/core.mil}
   %{dep:clojure/core.cljc}
   %{dep:clojure/string.mil}
   %{dep:clojure/string.cljc}
   %{dep:clojure/edn.mil}
   %{dep:clojure/edn.cljc}
   %{dep:cljs/reader.mil}
   %{dep:cljs/reader.cljc}
   %{dep:cljs/math.mil}
   %{dep:cljs/math.cljc}
   %{dep:clojure/core/protocols.cljc}
   %{dep:clojure/set.mil}
   %{dep:clojure/set.cljc}
   %{dep:clojure/data.mil}
   %{dep:clojure/data.cljc}
   %{dep:clojure/walk.mil}
   %{dep:clojure/walk.cljc}
   %{dep:clojure/zip.mil}
   %{dep:clojure/zip.cljc}
   -o
   lg_stdlib_native.ml)))

(alias
 (name stdlib-native)
 (deps lg_stdlib_native.ml lg_stdlib_native.state))

(rule
 (targets lg_stdlib_melange.ml lg_stdlib_melange.state)
 (deps
  clojure/core.mil
  clojure/core.cljc
  clojure/string.mil
  clojure/string.cljc
  clojure/edn.mil
  clojure/edn.cljc
  cljs/reader.mil
  cljs/reader.cljc
  cljs/math.mil
  cljs/math.cljc
  clojure/core/protocols.cljc
  clojure/set.mil
  clojure/set.cljc
  clojure/data.mil
  clojure/data.cljc
  clojure/walk.mil
  clojure/walk.cljc
  clojure/zip.mil
  clojure/zip.cljc
  %{lib:lg.runtime:lg_runtime.cma}
  ../bin/lg_cli.exe)
 (action
  (run
   %{exe:../bin/lg_cli.exe}
   --target
   melange
   --compile-files-state
   lg_stdlib_melange.state
   %{dep:clojure/core.mil}
   %{dep:clojure/core.cljc}
   %{dep:clojure/string.mil}
   %{dep:clojure/string.cljc}
   %{dep:clojure/edn.mil}
   %{dep:clojure/edn.cljc}
   %{dep:cljs/reader.mil}
   %{dep:cljs/reader.cljc}
   %{dep:cljs/math.mil}
   %{dep:cljs/math.cljc}
   %{dep:clojure/core/protocols.cljc}
   %{dep:clojure/set.mil}
   %{dep:clojure/set.cljc}
   %{dep:clojure/data.mil}
   %{dep:clojure/data.cljc}
   %{dep:clojure/walk.mil}
   %{dep:clojure/walk.cljc}
   %{dep:clojure/zip.mil}
   %{dep:clojure/zip.cljc}
   -o
   lg_stdlib_melange.ml)))

(alias
 (name stdlib-melange)
 (deps lg_stdlib_melange.ml lg_stdlib_melange.state))
