(rule
 (targets lg_stdlib_native.ml lg_stdlib_native.state)
 (deps
  clojure/core.mli
  clojure/core.cljc
  clojure/string.mli
  clojure/string.cljc
  clojure/edn.mli
  clojure/edn.cljc
  cljs/reader.mli
  cljs/reader.cljc
  cljs/math.mli
  cljs/math.cljc
  cljs/cache.cljc
  cljs/pprint.cljc
  clojure/core/protocols.cljc
  clojure/set.mli
  clojure/set.cljc
  clojure/data.mli
  clojure/data.cljc
  clojure/walk.mli
  clojure/walk.cljc
  clojure/zip.mli
  clojure/zip.cljc
  %{lib:lg.runtime:lg_runtime.cma}
  ../bin/lg_cli.exe)
 (action
  (run
   %{exe:../bin/lg_cli.exe}
   --target
   native
   --compile-files-state
   lg_stdlib_native.state
   %{dep:clojure/core.mli}
   %{dep:clojure/core.cljc}
   %{dep:clojure/string.mli}
   %{dep:clojure/string.cljc}
   %{dep:clojure/edn.mli}
   %{dep:clojure/edn.cljc}
   %{dep:cljs/reader.mli}
   %{dep:cljs/reader.cljc}
   %{dep:cljs/math.mli}
   %{dep:cljs/math.cljc}
   %{dep:cljs/cache.cljc}
   %{dep:cljs/pprint.cljc}
   %{dep:clojure/core/protocols.cljc}
   %{dep:clojure/set.mli}
   %{dep:clojure/set.cljc}
   %{dep:clojure/data.mli}
   %{dep:clojure/data.cljc}
   %{dep:clojure/walk.mli}
   %{dep:clojure/walk.cljc}
   %{dep:clojure/zip.mli}
   %{dep:clojure/zip.cljc}
   -o
   lg_stdlib_native.ml)))

(alias
 (name stdlib-native)
 (deps lg_stdlib_native.ml lg_stdlib_native.state))

(rule
 (targets lg_stdlib_melange.ml lg_stdlib_melange.state)
 (deps
  clojure/core.mli
  clojure/core.cljc
  clojure/string.mli
  clojure/string.cljc
  clojure/edn.mli
  clojure/edn.cljc
  cljs/reader.mli
  cljs/reader.cljc
  cljs/math.mli
  cljs/math.cljc
  cljs/cache.cljc
  cljs/pprint.cljc
  clojure/core/protocols.cljc
  clojure/set.mli
  clojure/set.cljc
  clojure/data.mli
  clojure/data.cljc
  clojure/walk.mli
  clojure/walk.cljc
  clojure/zip.mli
  clojure/zip.cljc
  %{lib:lg.runtime:lg_runtime.cma}
  ../bin/lg_cli.exe)
 (action
  (run
   %{exe:../bin/lg_cli.exe}
   --target
   melange
   --compile-files-state
   lg_stdlib_melange.state
   %{dep:clojure/core.mli}
   %{dep:clojure/core.cljc}
   %{dep:clojure/string.mli}
   %{dep:clojure/string.cljc}
   %{dep:clojure/edn.mli}
   %{dep:clojure/edn.cljc}
   %{dep:cljs/reader.mli}
   %{dep:cljs/reader.cljc}
   %{dep:cljs/math.mli}
   %{dep:cljs/math.cljc}
   %{dep:cljs/cache.cljc}
   %{dep:cljs/pprint.cljc}
   %{dep:clojure/core/protocols.cljc}
   %{dep:clojure/set.mli}
   %{dep:clojure/set.cljc}
   %{dep:clojure/data.mli}
   %{dep:clojure/data.cljc}
   %{dep:clojure/walk.mli}
   %{dep:clojure/walk.cljc}
   %{dep:clojure/zip.mli}
   %{dep:clojure/zip.cljc}
   -o
   lg_stdlib_melange.ml)))

(alias
 (name stdlib-melange)
 (deps lg_stdlib_melange.ml lg_stdlib_melange.state))
