(library
 (name repl_prototype)
 (modules repl_prototype)
 (modes byte)
 (libraries
  compiler-libs.toplevel
  lg
  lg.runtime
  lg.edn-backend.native
  lg_compiled_stdlib_native
  rrbvec
  unix))

(executable
 (name repl_prototype_test)
 (modules repl_prototype_test)
 (modes byte_complete)
 (libraries repl_prototype))

(rule
 (alias runtest)
 (deps ../../stdlib/lg_stdlib_native.state)
 (action
  (run %{exe:repl_prototype_test.bc.exe} %{dep:../../stdlib/lg_stdlib_native.state})))
