(library
 (name lg_repl)
 (public_name lg.repl)
 (modules
  nrepl_bencode
  nrepl_protocol
  nrepl_server
  protocol
  reader
  session
  socket_session
  watch_session)
 (modes byte)
 (libraries
  compiler-libs.toplevel
  lg
  lg.runtime
  lg.edn-backend.native
  lg.stdlib.native
  rrbvec
  yojson
  unix))
