(rule
 (target clojure_set_app_chunk.ml)
 (deps
  clojure_set_app.cljc
  ../../stdlib/lg_stdlib_native.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   native
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_set_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_additions_app_chunk.ml)
 (deps
  source_core_additions_app.cljc
  ../../stdlib/lg_stdlib_native.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   native
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_additions_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_nominal_predicates_app_chunk.ml)
 (deps
  source_core_nominal_predicates_app.cljc
  ../../stdlib/lg_stdlib_native.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   native
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_nominal_predicates_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_doseq_app_chunk.ml)
 (deps
  source_core_doseq_app.cljc
  ../../stdlib/lg_stdlib_native.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   native
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_doseq_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_doseq_native.ml)
 (deps ../../stdlib/lg_stdlib_native.ml source_core_doseq_app_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_native.ml})
    (cat %{dep:source_core_doseq_app_chunk.ml})))))

(executable
 (name source_core_doseq_native)
 (modules source_core_doseq_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.edn-backend.native lg.runtime re rrbvec))

(rule
 (alias runtest)
 (target source_core_doseq.actual)
 (deps source_core_doseq_native.exe source_core_doseq.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run %{exe:source_core_doseq_native.exe}))
   (diff %{dep:source_core_doseq.expected} %{target}))))

(rule
 (target source_core_doseq_app_melange_chunk.ml)
 (deps
  source_core_doseq_app.cljc
  ../../stdlib/lg_stdlib_melange.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   melange
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_melange.state}
   %{dep:source_core_doseq_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_doseq_melange.ml)
 (deps
  ../../stdlib/lg_stdlib_melange.ml
  source_core_doseq_app_melange_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_melange.ml})
    (cat %{dep:source_core_doseq_app_melange_chunk.ml})))))

(melange.emit
 (target source-core-doseq-melange)
 (alias source-core-doseq-melange)
 (module_systems es6)
 (modules source_core_doseq_melange)
 (compile_flags -w -27-32)
 (libraries lg.edn-backend lg.edn-backend.melange lg.runtime rrbvec))

(rule
 (alias runtest)
 (target source_core_doseq_melange.actual)
 (deps
  (alias source-core-doseq-melange)
  source-core-doseq-melange/test/stdlib/source_core_doseq_melange.js
  source_core_doseq.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run
     node
     %{dep:source-core-doseq-melange/test/stdlib/source_core_doseq_melange.js}))
   (diff %{dep:source_core_doseq.expected} %{target}))))

(rule
 (target source_core_nominal_predicates_native.ml)
 (deps
  ../../stdlib/lg_stdlib_native.ml
  source_core_nominal_predicates_app_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_native.ml})
    (cat %{dep:source_core_nominal_predicates_app_chunk.ml})))))

(executable
 (name source_core_nominal_predicates_native)
 (modules source_core_nominal_predicates_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.edn-backend.native lg.runtime re rrbvec))

(rule
 (alias runtest)
 (target source_core_nominal_predicates.actual)
 (deps
  source_core_nominal_predicates_native.exe
  source_core_nominal_predicates.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run %{exe:source_core_nominal_predicates_native.exe}))
   (diff %{dep:source_core_nominal_predicates.expected} %{target}))))

(rule
 (target source_core_nominal_predicates_app_melange_chunk.ml)
 (deps
  source_core_nominal_predicates_app.cljc
  ../../stdlib/lg_stdlib_melange.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   melange
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_melange.state}
   %{dep:source_core_nominal_predicates_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_nominal_predicates_melange.ml)
 (deps
  ../../stdlib/lg_stdlib_melange.ml
  source_core_nominal_predicates_app_melange_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_melange.ml})
    (cat %{dep:source_core_nominal_predicates_app_melange_chunk.ml})))))

(melange.emit
 (target source-core-nominal-predicates-melange)
 (alias source-core-nominal-predicates-melange)
 (module_systems es6)
 (modules source_core_nominal_predicates_melange)
 (compile_flags -w -27-32)
 (libraries lg.edn-backend lg.edn-backend.melange lg.runtime rrbvec))

(rule
 (alias runtest)
 (target source_core_nominal_predicates_melange.actual)
 (deps
  (alias source-core-nominal-predicates-melange)
  source-core-nominal-predicates-melange/test/stdlib/source_core_nominal_predicates_melange.js
  source_core_nominal_predicates.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run
     node
     %{dep:source-core-nominal-predicates-melange/test/stdlib/source_core_nominal_predicates_melange.js}))
   (diff %{dep:source_core_nominal_predicates.expected} %{target}))))

(rule
 (target source_core_lazy_transducer_app_chunk.ml)
 (deps
  source_core_lazy_transducer_app.cljc
  ../../stdlib/lg_stdlib_native.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   native
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_lazy_transducer_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_lazy_transducer_native.ml)
 (deps
  ../../stdlib/lg_stdlib_native.ml
  source_core_lazy_transducer_app_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_native.ml})
    (cat %{dep:source_core_lazy_transducer_app_chunk.ml})))))

(executable
 (name source_core_lazy_transducer_native)
 (modules source_core_lazy_transducer_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.edn-backend.native lg.runtime re rrbvec))

(rule
 (alias runtest)
 (target source_core_lazy_transducer.actual)
 (deps
  source_core_lazy_transducer_native.exe
  source_core_lazy_transducer.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run %{exe:source_core_lazy_transducer_native.exe}))
   (diff %{dep:source_core_lazy_transducer.expected} %{target}))))

(rule
 (target source_core_lazy_transducer_app_melange_chunk.ml)
 (deps
  source_core_lazy_transducer_app.cljc
  ../../stdlib/lg_stdlib_melange.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   melange
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_melange.state}
   %{dep:source_core_lazy_transducer_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_lazy_transducer_melange.ml)
 (deps
  ../../stdlib/lg_stdlib_melange.ml
  source_core_lazy_transducer_app_melange_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_melange.ml})
    (cat %{dep:source_core_lazy_transducer_app_melange_chunk.ml})))))

(melange.emit
 (target source-core-lazy-transducer-melange)
 (alias source-core-lazy-transducer-melange)
 (module_systems es6)
 (modules source_core_lazy_transducer_melange)
 (compile_flags -w -27-32)
 (libraries lg.edn-backend lg.edn-backend.melange lg.runtime rrbvec))

(rule
 (alias runtest)
 (target source_core_lazy_transducer_melange.actual)
 (deps
  (alias source-core-lazy-transducer-melange)
  source-core-lazy-transducer-melange/test/stdlib/source_core_lazy_transducer_melange.js
  source_core_lazy_transducer.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run
     node
     %{dep:source-core-lazy-transducer-melange/test/stdlib/source_core_lazy_transducer_melange.js}))
   (diff %{dep:source_core_lazy_transducer.expected} %{target}))))

(rule
 (alias runtest)
 (deps check_source_lazy_transducer_bootstrap.sh)
 (action
  (run sh %{dep:check_source_lazy_transducer_bootstrap.sh} ../..)))

(rule
 (target source_core_additions_native.ml)
 (deps ../../stdlib/lg_stdlib_native.ml source_core_additions_app_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_native.ml})
    (cat %{dep:source_core_additions_app_chunk.ml})))))

(executable
 (name source_core_additions_native)
 (modules source_core_additions_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.edn-backend.native lg.runtime re rrbvec))

(rule
 (alias runtest)
 (target source_core_additions.actual)
 (deps source_core_additions_native.exe source_core_additions.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run %{exe:source_core_additions_native.exe}))
   (diff %{dep:source_core_additions.expected} %{target}))))

(rule
 (target source_core_additions_app_melange_chunk.ml)
 (deps
  source_core_additions_app.cljc
  ../../stdlib/lg_stdlib_melange.state
  ../../bin/lg_cli.exe)
 (action
  (run
   %{exe:../../bin/lg_cli.exe}
   --target
   melange
   --compile-chunk-from
   %{dep:../../stdlib/lg_stdlib_melange.state}
   %{dep:source_core_additions_app.cljc}
   -o
   %{target})))

(rule
 (target source_core_additions_melange.ml)
 (deps
  ../../stdlib/lg_stdlib_melange.ml
  source_core_additions_app_melange_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_melange.ml})
    (cat %{dep:source_core_additions_app_melange_chunk.ml})))))

(melange.emit
 (target source-core-additions-melange)
 (alias source-core-additions-melange)
 (module_systems es6)
 (modules source_core_additions_melange)
 (compile_flags -w -27-32)
 (libraries lg.edn-backend lg.edn-backend.melange lg.runtime rrbvec))

(rule
 (alias runtest)
 (target source_core_additions_melange.actual)
 (deps
  (alias source-core-additions-melange)
  source-core-additions-melange/test/stdlib/source_core_additions_melange.js
  source_core_additions.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run
     node
     %{dep:source-core-additions-melange/test/stdlib/source_core_additions_melange.js}))
   (diff %{dep:source_core_additions.expected} %{target}))))

(rule
 (target clojure_set_native.ml)
 (deps ../../stdlib/lg_stdlib_native.ml clojure_set_app_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_native.ml})
    (cat %{dep:clojure_set_app_chunk.ml})))))

(executable
 (name clojure_set_native)
 (modules clojure_set_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.edn-backend.native lg.runtime re rrbvec))

(rule
 (alias runtest)
 (target clojure_set.actual)
 (deps clojure_set_native.exe clojure_set.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run %{exe:clojure_set_native.exe}))
   (diff %{dep:clojure_set.expected} %{target}))))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  clojure_set_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_set_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps check_compile_error.sh ../../stdlib/lg_stdlib_native.state
  reader_deregister_tag_parser_bad_arity.cljc ../../bin/lg_cli.exe)
 (action
  (run sh %{dep:check_compile_error.sh} %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:reader_deregister_tag_parser_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps check_compile_error.sh ../../stdlib/lg_stdlib_native.state
  source_core_hierarchy_bad_arity.cljc ../../bin/lg_cli.exe)
 (action
  (run sh %{dep:check_compile_error.sh} %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_hierarchy_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps check_compile_error.sh ../../stdlib/lg_stdlib_native.state
  clojure_zip_bad_arity.cljc ../../bin/lg_cli.exe)
 (action
  (run sh %{dep:check_compile_error.sh} %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_zip_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps check_compile_error.sh ../../stdlib/lg_stdlib_native.state
  reader_register_default_tag_parser_bad_arity.cljc ../../bin/lg_cli.exe)
 (action
  (run sh %{dep:check_compile_error.sh} %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:reader_register_default_tag_parser_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps check_compile_error.sh ../../stdlib/lg_stdlib_native.state
  reader_deregister_default_tag_parser_bad_arity.cljc ../../bin/lg_cli.exe)
 (action
  (run sh %{dep:check_compile_error.sh} %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:reader_deregister_default_tag_parser_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps check_compile_error.sh ../../stdlib/lg_stdlib_native.state
  clojure_walk_bad_keywordize_arity.cljc ../../bin/lg_cli.exe)
 (action
  (run sh %{dep:check_compile_error.sh} %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_walk_bad_keywordize_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_divide_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_divide_bad_arity.cljc}
   "divide called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_equiv_map_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_equiv_map_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_hash_map_lite_odd_keyvals.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_hash_map_lite_odd_keyvals.cljc}
   "No value supplied for key")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_key_test_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_key_test_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_reduceable_predicate_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_reduceable_predicate_bad_arity.cljc}
   "reduceable? called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_set_lite_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_set_lite_bad_arity.cljc}
   "set-lite called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_meta_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_meta_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_with_meta_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_with_meta_bad_arity.cljc}
   "with-meta called with unsupported macro arity 1")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_ifind_predicate_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_ifind_predicate_bad_arity.cljc}
   "ifind? called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_map_entry_predicate_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_map_entry_predicate_bad_arity.cljc}
   "map-entry? called with unsupported macro arity 2")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_regexp_predicate_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_regexp_predicate_bad_arity.cljc}
   "regexp? called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_volatile_predicate_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_volatile_predicate_bad_arity.cljc}
   "volatile? called with unsupported macro arity 2")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_hash_double_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_hash_double_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_hash_keyword_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_hash_keyword_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_hash_string_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_hash_string_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_array_index_of_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_array_index_of_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_iterate_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_iterate_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_tree_seq_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_tree_seq_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_tree_seq_bad_children.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_tree_seq_bad_children.cljc}
   "collection value is not seqable")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_partitionv_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_partitionv_bad_arity.cljc}
   "partitionv called with unsupported arity 1")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_partitionv_bad_pad.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_partitionv_bad_pad.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_add_to_string_hash_cache_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_add_to_string_hash_cache_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_flush_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_flush_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_areduce_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_areduce_bad_arity.cljc}
   "areduce called with unsupported macro arity 4")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_locking_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_locking_bad_arity.cljc}
   "locking called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_parse_long_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_parse_long_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_parse_long_bad_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_parse_long_bad_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_parse_double_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_parse_double_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_parse_double_bad_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_parse_double_bad_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_merge_with_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_merge_with_bad_arity.cljc}
   "unsupported arity")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_merge_with_bad_combiner.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_merge_with_bad_combiner.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_merge_with_bad_key_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_merge_with_bad_key_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_merge_with_bad_value_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_merge_with_bad_value_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_nan_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_nan_bad_arity.cljc}
   "NaN? expects 1 arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_infinite_bad_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_infinite_bad_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_keyword_identical_bad_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_keyword_identical_bad_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_hash_long_bad_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_hash_long_bad_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  clojure_set_non_set.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_set_non_set.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  clojure_set_mixed.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_set_mixed.cljc}
   "same element type")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_random_uuid_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_random_uuid_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_parse_uuid_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_parse_uuid_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_parse_uuid_bad_type.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_parse_uuid_bad_type.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_uuid_predicate_zero_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_uuid_predicate_zero_arity.cljc}
   "uuid? called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_doseq_zero_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_doseq_zero_arity.cljc}
   "doseq called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_doseq_non_vector.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_doseq_non_vector.cljc}
   "doseq requires a vector for its binding")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_doseq_odd_bindings.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_doseq_odd_bindings.cljc}
   "doseq requires an even number of forms in binding vector")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_doseq_invalid_keyword.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_doseq_invalid_keyword.cljc}
   "Invalid 'doseq' keyword :unless")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_uuid_predicate_two_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_uuid_predicate_two_arity.cljc}
   "uuid? called with unsupported macro arity 2")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_delay_predicate_zero_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_delay_predicate_zero_arity.cljc}
   "delay? called with unsupported macro arity 0")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_delay_predicate_two_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_delay_predicate_two_arity.cljc}
   "delay? called with unsupported macro arity 2")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  source_core_system_time_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:source_core_system_time_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_no_clojure_set_dispatch.sh
  ../../stdlib/upstream.edn
  ../../stdlib/clojure/set.cljc
  (source_tree ../../src))
 (action
  (run sh %{dep:check_no_clojure_set_dispatch.sh} ../..)))

(rule
 (alias source-namespace-migration)
 (deps
  check_source_namespace_migration.sh
  ../../stdlib/upstream.edn
  (source_tree ../../src))
 (action
  (run sh %{dep:check_source_namespace_migration.sh} ../..)))

(rule
 (alias source-core-bootstrap)
 (deps
  check_source_core_bootstrap.sh
  ../../stdlib/upstream.edn
  (source_tree ../../stdlib/clojure))
 (action
  (run sh %{dep:check_source_core_bootstrap.sh} ../..)))

(rule
 (alias runtest)
 (deps
  check_audited_core_boundaries.sh
  ../../script/extract_stdlib_manifest_status.clj
  ../../stdlib/upstream.edn)
 (action
  (run sh %{dep:check_audited_core_boundaries.sh} ../..)))

(rule
 (alias no-source-core-bit-dispatch)
 (deps
  check_no_source_core_bit_dispatch.sh
  ../../src/call_elaborator.ml
  ../../src/core_scalar.ml
  ../../src/type_inference.ml)
 (action
  (run sh %{dep:check_no_source_core_bit_dispatch.sh} ../..)))

(rule
 (alias no-source-core-fallbacks)
 (deps
  check_no_source_core_fallbacks.sh
  ../../script/extract_ocaml_string_dispatch.ml
  ../../src/call_elaborator.ml
  ../../src/core_boolean.ml
  ../../src/core_collection.ml
  ../../src/core_predicate.ml
  ../../src/core_scalar.ml
  ../../src/expression_support.ml
  ../../src/function_combinator_elaborator.ml
  ../../src/sequence_call_elaborator.ml
  ../../src/special_form_elaborator.ml
  ../../src/type_inference.ml)
 (action
  (run sh %{dep:check_no_source_core_fallbacks.sh} ../..)))

(rule
 (alias aggregate-stdlib-consumer)
 (deps
  check_aggregate_stdlib_consumer.sh
  dune
  ../../stdlib/dune)
 (action
  (run sh %{dep:check_aggregate_stdlib_consumer.sh} ../..)))

(rule
 (alias datascript-aggregate-stdlib)
 (deps
  check_datascript_aggregate_stdlib.sh
  ../datascript_conn_tests.inc)
 (action
  (run sh %{dep:check_datascript_aggregate_stdlib.sh} ../..)))

(rule
 (alias compile-files-from-stdlib)
 (targets
  aggregate_files_chunk.ml
  aggregate_files_chunk.ml.state
  aggregate_files_chunk.ml.with-state.ml)
 (deps
  check_compile_files_from.sh
  aggregate_provider.cljc
  aggregate_consumer.cljc
  ../../stdlib/lg_stdlib_native.state
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_files_from.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:aggregate_provider.cljc}
   %{dep:aggregate_consumer.cljc}
   aggregate_files_chunk.ml)))

(rule
 (target aggregate_files_native.ml)
 (deps ../../stdlib/lg_stdlib_native.ml aggregate_files_chunk.ml)
 (action
  (with-stdout-to
   %{target}
   (progn
    (cat %{dep:../../stdlib/lg_stdlib_native.ml})
    (cat %{dep:aggregate_files_chunk.ml})))))

(executable
 (name aggregate_files_native)
 (modules aggregate_files_native)
 (flags
  (:standard -w -27-32))
 (libraries lg.edn-backend.native lg.runtime re rrbvec))

(rule
 (alias runtest)
 (target aggregate_files.actual)
 (deps aggregate_files_native.exe aggregate_files.expected)
 (action
  (progn
   (with-stdout-to
    %{target}
    (run %{exe:aggregate_files_native.exe}))
   (diff %{dep:aggregate_files.expected} %{target}))))

(rule
 (alias source-reader-bootstrap)
 (deps
  check_source_reader_bootstrap.sh
  (source_tree ../../stdlib/clojure)
  (source_tree ../../stdlib/cljs)
  ../../script/extract_stdlib_manifest_status.clj
  ../../stdlib/upstream.edn
  ../../src/core_edn.ml
  ../../src/core_namespaces.ml)
 (action
  (run sh %{dep:check_source_reader_bootstrap.sh} ../..)))

(rule
 (alias source-string-bootstrap)
 (deps
  check_source_string_bootstrap.sh
  (source_tree ../../stdlib/clojure)
  ../../runtime/runtime_string.ml
  ../../src/core_namespaces.ml
  ../../src/expression_support.ml)
 (action
  (run sh %{dep:check_source_string_bootstrap.sh} ../..)))

(rule
 (alias source-data-bootstrap)
 (deps
  check_source_data_bootstrap.sh
  ../../script/extract_stdlib_manifest_status.clj
  ../../stdlib/upstream.edn
  ../../runtime/runtime_data.ml
  ../../src/core_protocols.ml
  ../../src/core_namespaces.ml
  (source_tree ../../stdlib/clojure))
 (action
  (run sh %{dep:check_source_data_bootstrap.sh} ../..)))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  clojure_data_equality_partition_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_data_equality_partition_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias runtest)
 (deps
  check_compile_error.sh
  ../../stdlib/lg_stdlib_native.state
  clojure_data_diff_similar_bad_arity.cljc
  ../../bin/lg_cli.exe)
 (action
  (run
   sh
   %{dep:check_compile_error.sh}
   %{exe:../../bin/lg_cli.exe}
   %{dep:../../stdlib/lg_stdlib_native.state}
   %{dep:clojure_data_diff_similar_bad_arity.cljc}
   "called with incompatible arguments")))

(rule
 (alias source-walk-bootstrap)
 (deps
  check_source_walk_bootstrap.sh
  ../../script/extract_stdlib_manifest_status.clj
  ../../stdlib/upstream.edn
  ../../runtime/runtime_walk.ml
  ../../src/core_namespaces.ml
  (source_tree ../../stdlib/clojure))
 (action
  (run sh %{dep:check_source_walk_bootstrap.sh} ../..)))

(rule
 (alias source-zip-bootstrap)
 (deps
  check_source_zip_bootstrap.sh
  ../../script/extract_stdlib_manifest_status.clj
  ../../stdlib/upstream.edn
  ../../src/core_namespaces.ml
  (source_tree ../../stdlib/clojure))
 (action
  (run sh %{dep:check_source_zip_bootstrap.sh} ../..)))

(rule
 (alias source-hierarchy-bootstrap)
 (deps
  check_source_hierarchy_bootstrap.sh
  ../../script/extract_stdlib_manifest_status.clj
  ../../stdlib/upstream.edn
  ../../src/call_elaborator.ml
  ../../stdlib/clojure/core.cljc)
 (action
  (run sh %{dep:check_source_hierarchy_bootstrap.sh} ../..)))

(alias
 (name runtest)
 (deps
  (alias aggregate-stdlib-consumer)
  (alias datascript-aggregate-stdlib)
  (alias no-source-core-fallbacks)
  (alias source-namespace-migration)
  (alias source-data-bootstrap)
  (alias source-hierarchy-bootstrap)
  (alias source-string-bootstrap)
  (alias source-walk-bootstrap)
  (alias source-zip-bootstrap)
  (alias ../../stdlib/stdlib-melange)))
